//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHK.MatejVlk.HorolezeckyPruvodce.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UHK.MatejVlk.HorolezeckyPruvodce.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikace obsahuje kompletní informace o oblíbené horolezecké oblasti Obrvégry a několik testovacích dat z dalších oblastí pro demonstraci kompletní funkčnosti aplikace.
        ///Informace jsou uspořádány podle geologické polohy, lezeckých oblastí a jim náležících sektorů. U každé horolezecké cesty je uvedena celá řada popisujících parametrů, jako je např. obtížnost, autor, charakter, způsob jištění, slovní popis či nákres. Uživatel má možnost data hierarchicky procházet nebo v nich vyhledávat. Přelezené cesty je mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutAppPage_AboutText {
            get {
                return ResourceManager.GetString("AboutAppPage_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string AboutAppPage_Title {
            get {
                return ResourceManager.GetString("AboutAppPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verze: 1.0.
        /// </summary>
        internal static string AboutAppPage_Version {
            get {
                return ResourceManager.GetString("AboutAppPage_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Průměrná obtížnost:.
        /// </summary>
        internal static string AccountPage_AverageDifficulty {
            get {
                return ResourceManager.GetString("AccountPage_AverageDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit uživatele.
        /// </summary>
        internal static string AccountPage_CreateAccount {
            get {
                return ResourceManager.GetString("AccountPage_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypadá to, že ještě nemáte vytvořený účet. Napravte to pomocí formuláře níže a využijte tak všech možností aplikace..
        /// </summary>
        internal static string AccountPage_NoUser {
            get {
                return ResourceManager.GetString("AccountPage_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet cest v deníčku:.
        /// </summary>
        internal static string AccountPage_NumberOfDiaryRoutes {
            get {
                return ResourceManager.GetString("AccountPage_NumberOfDiaryRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cest:.
        /// </summary>
        internal static string AccountPage_NumberOfRoutes {
            get {
                return ResourceManager.GetString("AccountPage_NumberOfRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet.
        /// </summary>
        internal static string AccountPage_Title {
            get {
                return ResourceManager.GetString("AccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet vytvořen.
        /// </summary>
        internal static string AccountPage_UserCreated {
            get {
                return ResourceManager.GetString("AccountPage_UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        internal static string AccountPage_UserName {
            get {
                return ResourceManager.GetString("AccountPage_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapsat do deníčku.
        /// </summary>
        internal static string AddDiaryPage_AddTitle {
            get {
                return ResourceManager.GetString("AddDiaryPage_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum přelezu.
        /// </summary>
        internal static string AddDiaryPage_Date {
            get {
                return ResourceManager.GetString("AddDiaryPage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit záznam v deníčku.
        /// </summary>
        internal static string AddDiaryPage_EditTitle {
            get {
                return ResourceManager.GetString("AddDiaryPage_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnocení.
        /// </summary>
        internal static string AddDiaryPage_Feeling {
            get {
                return ResourceManager.GetString("AddDiaryPage_Feeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        internal static string AddDiaryPage_Note {
            get {
                return ResourceManager.GetString("AddDiaryPage_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cestu se nepodařilo uložit do deníčku..
        /// </summary>
        internal static string AddDiaryPage_NotSaved {
            get {
                return ResourceManager.GetString("AddDiaryPage_NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spolulezec.
        /// </summary>
        internal static string AddDiaryPage_Partner {
            get {
                return ResourceManager.GetString("AddDiaryPage_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta byla uložena do deníčku..
        /// </summary>
        internal static string AddDiaryPage_Saved {
            get {
                return ResourceManager.GetString("AddDiaryPage_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styl přelezu.
        /// </summary>
        internal static string AddDiaryPage_Style {
            get {
                return ResourceManager.GetString("AddDiaryPage_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K této poloze nebyl zadán žádný popis..
        /// </summary>
        internal static string AreaListPage_NoLocationInfo {
            get {
                return ResourceManager.GetString("AreaListPage_NoLocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblasti.
        /// </summary>
        internal static string AreaListPage_Title {
            get {
                return ResourceManager.GetString("AreaListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat cestu z deníčku?.
        /// </summary>
        internal static string DiaryDeleteDialog_Message {
            get {
                return ResourceManager.GetString("DiaryDeleteDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat cestu.
        /// </summary>
        internal static string DiaryDeleteDialog_Title {
            get {
                return ResourceManager.GetString("DiaryDeleteDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francouzská.
        /// </summary>
        internal static string GradingSystem_French {
            get {
                return ResourceManager.GetString("GradingSystem_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jizerská.
        /// </summary>
        internal static string GradingSystem_Jizerska {
            get {
                return ResourceManager.GetString("GradingSystem_Jizerska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiná.
        /// </summary>
        internal static string GradingSystem_Other {
            get {
                return ResourceManager.GetString("GradingSystem_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saská pískovcová.
        /// </summary>
        internal static string GradingSystem_Saxon {
            get {
                return ResourceManager.GetString("GradingSystem_Saxon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAA.
        /// </summary>
        internal static string GradingSystem_UIAA {
            get {
                return ResourceManager.GetString("GradingSystem_UIAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        internal static string GradingSystem_USA {
            get {
                return ResourceManager.GetString("GradingSystem_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O APLIKACI.
        /// </summary>
        internal static string HomePage_AboutApp {
            get {
                return ResourceManager.GetString("HomePage_AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚČET.
        /// </summary>
        internal static string HomePage_Account {
            get {
                return ResourceManager.GetString("HomePage_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor: Matěj Vlk.
        /// </summary>
        internal static string HomePage_Author {
            get {
                return ResourceManager.GetString("HomePage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedra informatiky a kvantitativních metod.
        /// </summary>
        internal static string HomePage_Department {
            get {
                return ResourceManager.GetString("HomePage_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakulta informatiky a managementu.
        /// </summary>
        internal static string HomePage_Faculty {
            get {
                return ResourceManager.GetString("HomePage_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studijní obor: Aplikovaná informatika.
        /// </summary>
        internal static string HomePage_FieldOfStudy {
            get {
                return ResourceManager.GetString("HomePage_FieldOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRŮVODCE.
        /// </summary>
        internal static string HomePage_Guide {
            get {
                return ResourceManager.GetString("HomePage_Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horolezecký průvodce pro Android.
        /// </summary>
        internal static string HomePage_Name {
            get {
                return ResourceManager.GetString("HomePage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hradec Králové, 2017.
        /// </summary>
        internal static string HomePage_Place {
            get {
                return ResourceManager.GetString("HomePage_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLEDÁNÍ.
        /// </summary>
        internal static string HomePage_Search {
            get {
                return ResourceManager.GetString("HomePage_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedoucí práce: doc. Ing. Filip Malý, Ph.D..
        /// </summary>
        internal static string HomePage_Supervisor {
            get {
                return ResourceManager.GetString("HomePage_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakalářská práce.
        /// </summary>
        internal static string HomePage_Thesis {
            get {
                return ResourceManager.GetString("HomePage_Thesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOROLEZECKÝ PRŮVODCE.
        /// </summary>
        internal static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univerzita Hradec Králové.
        /// </summary>
        internal static string HomePage_University {
            get {
                return ResourceManager.GetString("HomePage_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polohy.
        /// </summary>
        internal static string LocationListPage_Title {
            get {
                return ResourceManager.GetString("LocationListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklon.
        /// </summary>
        internal static string RouteDetailPage_Angle {
            get {
                return ResourceManager.GetString("RouteDetailPage_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string RouteDetailPage_Author {
            get {
                return ResourceManager.GetString("RouteDetailPage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        internal static string RouteDetailPage_Description {
            get {
                return ResourceManager.GetString("RouteDetailPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtíže.
        /// </summary>
        internal static string RouteDetailPage_Difficulties {
            get {
                return ResourceManager.GetString("RouteDetailPage_Difficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasifikace.
        /// </summary>
        internal static string RouteDetailPage_Grade {
            get {
                return ResourceManager.GetString("RouteDetailPage_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stupnice obtížnosti.
        /// </summary>
        internal static string RouteDetailPage_GradingSystem {
            get {
                return ResourceManager.GetString("RouteDetailPage_GradingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka.
        /// </summary>
        internal static string RouteDetailPage_Length {
            get {
                return ResourceManager.GetString("RouteDetailPage_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        internal static string RouteDetailPage_Note {
            get {
                return ResourceManager.GetString("RouteDetailPage_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jištění.
        /// </summary>
        internal static string RouteDetailPage_Protection {
            get {
                return ResourceManager.GetString("RouteDetailPage_Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hornina.
        /// </summary>
        internal static string RouteDetailPage_RockType {
            get {
                return ResourceManager.GetString("RouteDetailPage_RockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umístění.
        /// </summary>
        internal static string RouteDetailPage_Sector {
            get {
                return ResourceManager.GetString("RouteDetailPage_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ cesty.
        /// </summary>
        internal static string RouteDetailPage_Type {
            get {
                return ResourceManager.GetString("RouteDetailPage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neznámý.
        /// </summary>
        internal static string RouteDetailPage_UnknownAuthor {
            get {
                return ResourceManager.GetString("RouteDetailPage_UnknownAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K tomuto sektoru nebyl zadán žádný popis..
        /// </summary>
        internal static string RouteListPage_NoSectorInfo {
            get {
                return ResourceManager.GetString("RouteListPage_NoSectorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesty.
        /// </summary>
        internal static string RouteListPage_Title {
            get {
                return ResourceManager.GetString("RouteListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezené oblasti.
        /// </summary>
        internal static string SearchPage_FoundAreasTitle {
            get {
                return ResourceManager.GetString("SearchPage_FoundAreasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezené polohy.
        /// </summary>
        internal static string SearchPage_FoundLocationsTitle {
            get {
                return ResourceManager.GetString("SearchPage_FoundLocationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezené cesty.
        /// </summary>
        internal static string SearchPage_FoundRoutesTitle {
            get {
                return ResourceManager.GetString("SearchPage_FoundRoutesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezené sektory.
        /// </summary>
        internal static string SearchPage_FoundSectorsTitle {
            get {
                return ResourceManager.GetString("SearchPage_FoundSectorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte název hledaného objektu..
        /// </summary>
        internal static string SearchPage_Info {
            get {
                return ResourceManager.GetString("SearchPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledaná fráze musí mít minimálně 2 znaky..
        /// </summary>
        internal static string SearchPage_MinLength {
            get {
                return ResourceManager.GetString("SearchPage_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string SearchPage_Name {
            get {
                return ResourceManager.GetString("SearchPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najít.
        /// </summary>
        internal static string SearchPage_Search {
            get {
                return ResourceManager.GetString("SearchPage_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledání.
        /// </summary>
        internal static string SearchPage_Title {
            get {
                return ResourceManager.GetString("SearchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K této oblasti nebyl zadán žádný popis..
        /// </summary>
        internal static string SectorListPage_NoAreaInfo {
            get {
                return ResourceManager.GetString("SectorListPage_NoAreaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektory.
        /// </summary>
        internal static string SectorListPage_Title {
            get {
                return ResourceManager.GetString("SectorListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámá.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
